{% set name = "flac" %}
{% set version = "1.3.1" %}
{% set sha256 = "e0c23c92af0aac830683a6ab6784dd0c11aaf04249709b9d600675b3b2441c3e" %}

package:
  name: lib{{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/xiph/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
   number: 3
   string: py{{ python | replace(".", "") }}_{{ PKG_BUILDNUM }}

requirements:
  build:
    - autoconf  # [unix]
    - automake  # [unix]
    - libtool  # [unix]
    - pkg-config  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}
    - libstdcxx-ng  {{ libstdcxx }}
  host:
    - gettext  # [unix]
    - libogg {{ libogg }}
    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}
    - libstdcxx-ng  {{ libstdcxx }}
  run:
    - libogg {{ libogg }} 

test:
  requires:
    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}
    - libstdcxx-ng  {{ libstdcxx }}

  commands:
    - test -f $PREFIX/bin/flac  # [unix]
    - test -f $PREFIX/bin/metaflac  # [unix]
    - test -f $PREFIX/lib/libFLAC.so  # [linux]
    - test -f $PREFIX/lib/libFLAC++.so  # [linux]
    
about:
  home: https://www.xiph.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.Xiph
  summary: "Flac audio format"
  description: Free Lossless Audio Codec.
  doc_url: https://wiki.xiph.org/

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
